### PR TITLE
Milestone 3

### LINKED ISSUE #1: A person, a bench, and some violence
The goal of this milestone is to create a basic system of interaction with the following elements:
- Object types (person, bench)
- Object properties (stats, images, contexts/actions)
- Object state management (instantiation, update, destroy)
- Object control (directly control player, indirectly interact with bench)

### PR DESCRIPTION
**Pull request by smileynet**
Adds the following features:
    Object types (person, bench)
    Object properties (stats, images, contexts/actions)
    Object state management (instantiation, update, destroy)
    Object control (directly control player, indirectly interact with bench)

### CODE REVIEW

**Comment by dwhitehead** [comment]
Working on this but fighting windows to get it running

**Comment by smileynet** [comment]
> Working on this but fighting windows to get it running

I was able to test on my Windows box and didn't hit any issues, let me know if there's something specific you're running in to?

**Comment by dwhitehead** [comment]
More about my setup I’ll give more time to this tonight

-- 
Sent from my mobile

**Comment by dwhitehead** [comment]
compiled and run closing

**Pull request merged**
